apiVersion: arca.coreweave.com/v1alpha1
kind: AppManifest
spec:
  apps:
    - name: nginx
      path: ./apps/nginx
      type: kustomize
      targets:
        - cluster: arca-customer
          namespace: default
      syncPolicy:
        interval: 5m
        prune: true
        selfHeal: true
