alertmanager:
  enabled: false

prometheus-pushgateway:
  enabled: false

server:
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  persistentVolume:
    enabled: false

nodeExporter:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi
